### ISSUE TITLE
Ошибка сборки

### ISSUE THREAD

**Issue by stepan14041999** [GravitLauncher/GravitGuard#1]
При попытке сборки проекта выпадает следующая ошибка в Visual Studio 2019

`Повторная сборка начата…
1>------ Перестроение всех файлов начато: проект: MinHook, Конфигурация: ReleaseStatic Win32 ------
1>buffer.c
1>hde32.c
1>hde64.c
1>hook.c
1>C:\Users\Stepa\source\repos\GravitGuard\MinHook\hook.c(33,10): fatal error C1083: Не удается открыть файл включение: ../include/MinHook.h: No such file or directory,
1>trampoline.c
1>Сборка проекта "MinHook.vcxproj" завершена с ошибкой.
2>------ Перестроение всех файлов начато: проект: GravitGuard, Конфигурация: ReleaseStatic Win32 ------
2>pch.cpp
2>base64.cpp
2>C:\Users\Stepa\source\repos\GravitGuard\GravitGuard\base64.cpp(68,57): warning C4267: =: преобразование из "size_t" в "unsigned char"; возможна потеря данных
2>C:\Users\Stepa\source\repos\GravitGuard\GravitGuard\base64.cpp(85,56): warning C4267: =: преобразование из "size_t" в "unsigned char"; возможна потеря данных
2>C:\Users\Stepa\source\repos\GravitGuard\GravitGuard\base64.cpp(111,20): warning C4018: <: несоответствие типов со знаком и без знака
2>dllmain.cpp
2>globals.cpp
2>C:\Users\Stepa\source\repos\GravitGuard\GravitGuard\GuardDetour.h(2,10): fatal error C1083: Не удается открыть файл включение: MinHook.h: No such file or directory,
2>GravitGuard.cpp
2>C:\Users\Stepa\source\repos\GravitGuard\GravitGuard\GuardDetour.h(2,10): fatal error C1083: Не удается открыть файл включение: MinHook.h: No such file or directory,
2>GravitGuardAPI.cpp
2>C:\Users\Stepa\source\repos\GravitGuard\GravitGuard\GravitGuardAPI.cpp(4,10): fatal error C1083: Не удается открыть файл включение: MinHook.h: No such file or directory,
2>GuardDetour.cpp
2>C:\Users\Stepa\source\repos\GravitGuard\GravitGuard\GuardDetour.h(2,10): fatal error C1083: Не удается открыть файл включение: MinHook.h: No such file or directory,
2>LicenseChecker.cpp
2>C:\Users\Stepa\source\repos\GravitGuard\GravitGuard\LicenseChecker.cpp(40,13): warning C4244: инициализация: преобразование "std::streamoff" в "int", возможна потеря данных
2>C:\Users\Stepa\source\repos\GravitGuard\GravitGuard\LicenseChecker.cpp(82,39): warning C4267: =: преобразование из "size_t" в "unsigned short"; возможна потеря данных
2>Logger.cpp
2>MagicFunctionTable.cpp
2>Сборка проекта "GravitGuard.vcxproj" завершена с ошибкой.
3>------ Перестроение всех файлов начато: проект: LicenseGenerator, Конфигурация: ReleaseStatic Win32 ------
4>------ Перестроение всех файлов начато: проект: JavaWrapper, Конфигурация: ReleaseStatic Win32 ------
3>LicenseGenerator.cpp
4>JavaWrapper.cpp
3>C:\Users\Stepa\source\repos\GravitGuard\GravitGuard\base64.cpp(68,57): warning C4267: =: преобразование из "size_t" в "unsigned char"; возможна потеря данных
3>C:\Users\Stepa\source\repos\GravitGuard\GravitGuard\base64.cpp(85,56): warning C4267: =: преобразование из "size_t" в "unsigned char"; возможна потеря данных
3>C:\Users\Stepa\source\repos\GravitGuard\GravitGuard\base64.cpp(111,20): warning C4018: <: несоответствие типов со знаком и без знака
3>C:\Users\Stepa\source\repos\GravitGuard\LicenseGenerator\LicenseGenerator.cpp(31,13): warning C4244: инициализация: преобразование "std::streamoff" в "int", возможна потеря данных
3>Сборка проекта "LicenseGenerator.vcxproj" завершена с ошибкой.
========== Перестроение всех проектов: успешно: 0, с ошибками: 4, пропущено: 0 ==========
`

**Comment by typicalcoder** [comment]
https://github.com/TsudaKageyu/minhook
