### ISSUE TITLE
GravitGuard.log - весит очень много спустя минуту

### ISSUE THREAD

**Issue by leadertv** [GravitLauncher/GravitGuard#4]
Собрал из исходников Антиинжект, закинул в папку guard лаунчcервера, сделал build
Перекачал лаунчер, и после запуска игры, заметил что GravitGuard.log весит очень много! Защита при этом работает.
Как отключить логирование?

Более того, последующие запуски лаунчера иногда не приводят ни к чему, приходится убивать процесс антиижекта через диспетчер задач.

А если в config.h сделать так:
```
#pragma once
#define GUARD_EXPORT    __declspec(dllexport)
#define GUARD_NO_LICENSE_CHECK
//#define GUARD_DEBUG_MODE
#define GUARD_WARN_MODE
```
То при сборке появляется ошибка: _Метка LdrLoadDllOriginal не была определена и на этом всё останавливается._

**Comment by gravit0** [comment]
Опция GUARD_WARN_MODE **отключает защиту, преводя ошибки в предупреждения**. Вам нужно отключить только отладку
Последнее исправление должно помочь

**Comment by leadertv** [comment]
> Опция GUARD_WARN_MODE **отключает защиту, преводя ошибки в предупреждения**. Вам нужно отключить только отладку Последнее исправление должно помочь

Что-то пошло не так. Отключив отладку, получаем ошибку и выход.

> C:\Program Files\BellSoft\LibericaJDK-8-Full\bin\server\jvm.dll
> OpenJDK 64-Bit Server VM warning: Using incremental CMS is deprecated and will likely be removed in a future release
> **Process exit code -1073741819**

Конфигурация вот такая, из исходных настроек, закомментировал только отладку, остальное не трогал:
```
#pragma once
#define GUARD_EXPORT    __declspec(dllexport)
#define GUARD_NO_LICENSE_CHECK
//#define GUARD_DEBUG_MODE
//#define GUARD_WARN_MODE
```

**Comment by gravit0** [comment]
> Process exit code -1073741819
Строго следуйте инструкции в README
Если не поможет откройте новый issue с более подробной информацией
