### ISSUE TITLE
FlsGetValue, виснет процесс запуска клиента

### ISSUE THREAD

**Issue by kwetroi** [GravitLauncher/GravitGuard#5]
Здравствуйте. При запуске клиента 1.7.10-forge с GravitGuard запуск клиента виснет на стадии FlsGetValue. Сборка античита последняя, пробовал много разных Java, в том числе и BellSoft.

Пример лога:
https://hastebin.com/dojixalapo.css
[guard.log](https://github.com/GravitLauncher/GravitGuard/files/10366563/guard.log)

Если будут дополнительные вопросы или нужно будет что-то протестировать, просьба написать в Discord: kwetroi#0195

**Comment by leadertv** [comment]
Абсолютно тоже самое, и это ещё в режиме отладки, а бывает и так, что даже запускается клиент, но переоткрыв лаунчер, клиент дальше отказывается запускаться, а процесс "antiinjectName.exe" висит в процессах даже когда лаунчер закрыт. Убив процесс, с третьей попытки может и запустится.
В общем, как-то вот так нестабильно это всё работает. А если и запустился клиент, то защита от инжекта нормально срабатывает. Но в дебаг режиме логи потом гигабайты вешают за вечер.

**Comment by gravit0** [comment]
Это извесная проблема. Я не знаю чем она вызвана и как её решить
Если предоставите список ПО на проблемных компьютерах это может помочь выявить причину

**Comment by gravit0** [comment]
Попробуйте поочередно отключить оверлеи(NVIDIA Experience, Steam и другие)

**Comment by kwetroi** [comment]
Пробовал отключать разные программы: OBS, Discord, Nvidia Control Panel, Steam, Xbox Game Bar, Riot Vanguard. Проблема не ушла.
Почему античит иногда использует системные DLL? https://hastebin.com/ohiculoxux.css
Список ПО: https://imgur.com/a/KpvCzvA
Проблема как раз у меня на ПК :)

**Comment by gravit0** [comment]
NVIDIA Control Panel это не NVIDIA Experience. Проверьте еще раз, у вас как раз оно установлено

**Comment by kwetroi** [comment]
Удалил NVIDIA Experience, появились новые логи:
https://hastebin.com/acefedunem.css

**Comment by gravit0** [comment]
Тут нет ошибок. Проблема с FlsGetValue решена?

**Comment by leadertv** [comment]
> Тут нет ошибок. Проблема с FlsGetValue решена?

У него там краш. На самом деле и у меня тоже-самое. Но с периодичностью. Например версия 1.19.2 уже не стартует. А 1.7.10 работает нормально.

> [9.1.2023 21:6:2:493]	[TRACE]	[CheckStacktrace]	C:\Program Files\BellSoft\LibericaJRE-8-Full\bin\awt.dll
[9.1.2023 21:6:2:493]	[TRACE]	[CheckStacktrace]	Unknown memory region
[9.1.2023 21:6:2:495]	[TRACE]	[Process]	ThreadAttach
[9.1.2023 21:6:2:495]	[TRACE]	[getProcAddress]	FlsGetValue
[9.1.2023 21:6:2:495]	[CRASH]	[getProcAddress]	FlsGetValue

**Comment by kwetroi** [comment]
> Тут нет ошибок. Проблема с FlsGetValue решена?
Нет, клиент так и не запустился. Процесс запуска повис.
Решение проблемы удалить NVIDIA Experience, как мне кажется это не решение. Во-первых, пока к стабильному старту клиента это не привело. Во-вторых, все игроки не будут удалять такие стандартные программы.

**Comment by gravit0** [comment]
Достаточно отключить оверлей NVIDIA Experience в настройках вместо удаления всей программы
Обновитесь до актуальной версии лаунчера и рантайма - там проблемы с зависанием из за слишком большого объема логов решены
1.19.2 не работает с ошибкой FlsGetValue?
Отключите оверлей NVIDIA Experience

**Comment by kwetroi** [comment]
> Достаточно отключить оверлей NVIDIA Experience в настройках вместо удаления всей программы Обновитесь до актуальной версии лаунчера и рантайма - там проблемы с зависанием из за слишком большого объема логов решены 1.19.2 не работает с ошибкой FlsGetValue? Отключите оверлей NVIDIA Experience

Оверлей NVIDIA Experience уже был отключен, ошибка пропала только после полного удаления. Лаунчер работает на версии 5.3.4-1, возможно, я рантайм не обновил.

**Comment by gravit0** [comment]
Баг исправлен https://github.com/GravitLauncher/GravitGuard/commit/4beaf2797dfec0aaef1ef1887720a79466b86340
